version: "3"

services:
  db:
    container_name: "db"
    build: ./db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=casinoplus
      - POSTGRES_PASSWORD=casinoplus
      - POSTGRES_DB=casinoplus

      # *** テスト用に全ホストからアクセス許可 ***
      - POSTGRES_HOST_AUTH_METHOD=trust
      # ************************************

    volumes:
      - ./db:/docker-entrypoint-initdb.d # ファイルをマウントしてDBを立ち上げた後でSQLを自動実行
    networks:
      - app-net # ネットワークを指定して、コンテナ間で通信する

  webapi:
    depends_on:
        - db # db起動後に立ち上げる
    links:
        - db:db
    container_name: "webapi"
    build: ./webapi
    # tty: true
    ports:
      - 3000:3000
    volumes:
      - ./webapi:/webapi
      - /webapi/node_modules # ホスト側には node_modules がなくてもOK "."は不要なので注意
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

