version: "3"

services:
  mongo:
    container_name: "mongo"
    build: ./mongo
    ports:
      - "27018:27017"
    volumes:
      # - ./mongo/db:/data/db # データを永続化したい時に有効にする
      # - ./mongo/configdb:/data/configdb
      - ./mongo/init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
      TZ: Asia/Tokyo
    networks:
      - app-net
    command: --quiet

  webapi:
    depends_on:
      - mongo # db起動後に立ち上げる
    links:
      - mongo:mongo
    container_name: "webapi"
    build: ./webapi
    ports:
      - 3000:3000
    volumes:
      - ./webapi:/webapi
      - /webapi/node_modules # ホスト側には node_modules がなくてもOK "."は不要なので注意
    networks:
      - app-net
    command: npm run debug

networks:
  app-net:
    driver: bridge
